import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { 
  Users, 
  DollarSign, 
  TrendingUp, 
  Clock, 
  MoreHorizontal, 
  Calendar, 
  Plus,
  ArrowRight
} from "lucide-react";
import { motion } from "framer-motion";

const stats = [
  {
    label: "Total pipeline value",
    value: "$284,500",
    icon: DollarSign,
  },
  {
    label: "Conversion rate",
    value: "34%",
    icon: TrendingUp,
  },
  {
    label: "Avg deal cycle",
    value: "12 days",
    icon: Clock,
  },
];

const columns = [
  {
    id: "new",
    title: "New",
    leads: [
      {
        id: "1",
        client: "Morrison Family",
        event: "Morrison Wedding Reception",
        date: "Oct 12, 2024",
        guests: 150,
        amount: "$15,000",
      },
      {
        id: "2",
        client: "Jenkins Corp",
        event: "City Health Summit",
        date: "Nov 05, 2024",
        guests: 300,
        amount: "$45,000",
      },
      {
        id: "3",
        client: "Robert Johnson",
        event: "Johnson Family Reunion",
        date: "Sep 28, 2024",
        guests: 80,
        amount: "$8,500",
      },
    ],
  },
  {
    id: "proposal",
    title: "Proposal Sent",
    leads: [
      {
        id: "4",
        client: "Elena Rivera",
        event: "Rivera Quinceañera",
        date: "Dec 15, 2024",
        guests: 200,
        amount: "$22,000",
      },
      {
        id: "5",
        client: "Marcus Lee",
        event: "Global Edu Conference",
        date: "Jan 20, 2025",
        guests: 500,
        amount: "$75,000",
      },
    ],
  },
  {
    id: "contract",
    title: "Contract Sent",
    leads: [
      {
        id: "6",
        client: "Alice Miller",
        event: "Miller 50th Birthday",
        date: "Oct 30, 2024",
        guests: 120,
        amount: "$12,500",
      },
      {
        id: "7",
        client: "Tech Startups Inc",
        event: "Startup Launch Party",
        date: "Nov 12, 2024",
        guests: 250,
        amount: "$35,000",
      },
    ],
  },
  {
    id: "booked",
    title: "Booked",
    leads: [
      {
        id: "8",
        client: "TechCorp",
        event: "TechCorp Annual Gala",
        date: "Dec 10, 2024",
        guests: 800,
        amount: "$120,000",
        autoGenerated: true,
      },
    ],
  },
  {
    id: "won",
    title: "Won",
    leads: [
      {
        id: "9",
        client: "Winter Foundation",
        event: "Winter Wonderland Ball",
        date: "Dec 22, 2024",
        guests: 400,
        amount: "$55,000",
      },
    ],
  },
];

export default function Index() {
  return (
    <DashboardLayout>
      <div className="flex flex-col h-full bg-[#09090b]">
        {/* Top Bar Stats */}
        <div className="border-b border-[#1f1f23] bg-[#09090b]/50 backdrop-blur-xl px-8 py-6">
          <div className="flex flex-wrap items-center gap-12 max-w-[1600px]">
            {stats.map((stat) => (
              <div key={stat.label} className="flex flex-col gap-1">
                <span className="text-[11px] font-bold uppercase tracking-[0.15em] text-zinc-500">
                  {stat.label}
                </span>
                <div className="flex items-center gap-2">
                  <span className="text-2xl font-bold text-zinc-100 tracking-tight">
                    {stat.value}
                  </span>
                </div>
              </div>
            ))}
            <div className="ml-auto flex items-center gap-3">
              <button className="h-9 px-4 rounded-md border border-zinc-800 bg-zinc-900 text-xs font-semibold text-zinc-300 hover:bg-zinc-800 transition-colors">
                View Reports
              </button>
              <button className="h-9 px-4 rounded-md bg-zinc-100 text-xs font-bold text-zinc-950 hover:bg-zinc-200 transition-colors flex items-center gap-2">
                <Plus className="h-3.5 w-3.5" />
                Add Lead
              </button>
            </div>
          </div>
        </div>

        {/* Kanban Board Container */}
        <div className="flex-1 overflow-x-auto overflow-y-hidden p-8">
          <div className="flex gap-6 h-full min-w-max max-w-[1600px]">
            {columns.map((column) => (
              <div key={column.id} className="w-[300px] flex flex-col gap-4">
                <div className="flex items-center justify-between px-1">
                  <div className="flex items-center gap-2.5">
                    <h3 className="text-[13px] font-bold text-zinc-400">
                      {column.title}
                    </h3>
                    <span className="flex items-center justify-center h-5 w-5 rounded-md bg-zinc-900 border border-zinc-800 text-[10px] font-bold text-zinc-500">
                      {column.leads.length}
                    </span>
                  </div>
                  <button className="p-1 hover:bg-zinc-900 rounded-md transition-colors">
                    <MoreHorizontal className="h-4 w-4 text-zinc-600" />
                  </button>
                </div>

                <div className="flex-1 flex flex-col gap-3 rounded-xl bg-zinc-950/50 p-2 border border-zinc-900/50">
                  {column.leads.map((lead) => (
                    <motion.div
                      key={lead.id}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.2 }}
                    >
                      <Card className="bg-zinc-900 border-zinc-800 hover:border-zinc-700 transition-all cursor-pointer group shadow-none">
                        <CardContent className="p-4 space-y-4">
                          {lead.autoGenerated && (
                            <div className="flex">
                              <Badge className="bg-emerald-500/10 text-emerald-400 border-emerald-500/20 text-[10px] h-5 rounded px-2 font-bold tracking-tight uppercase">
                                Auto-Generated Project
                              </Badge>
                            </div>
                          )}
                          
                          <div>
                            <div className="flex justify-between items-start mb-1">
                              <h4 className="text-sm font-bold text-zinc-100 group-hover:text-white transition-colors tracking-tight">
                                {lead.event}
                              </h4>
                              <span className="text-xs font-bold text-zinc-100">
                                {lead.amount}
                              </span>
                            </div>
                            <span className="text-[11px] font-medium text-zinc-500">
                              {lead.client}
                            </span>
                          </div>

                          <div className="flex items-center justify-between pt-1">
                            <div className="flex items-center gap-3">
                              <div className="flex items-center gap-1.5 text-[10px] font-bold text-zinc-500 uppercase tracking-wider">
                                <Calendar className="h-3 w-3 opacity-50" />
                                {lead.date}
                              </div>
                              <div className="flex items-center gap-1.5 text-[10px] font-bold text-zinc-500 uppercase tracking-wider">
                                <Users className="h-3 w-3 opacity-50" />
                                {lead.guests}
                              </div>
                            </div>
                            <div className="flex -space-x-2">
                                <div className="h-6 w-6 rounded-full border-2 border-zinc-900 bg-zinc-800 overflow-hidden ring-1 ring-zinc-800">
                                  <img src={`https://avatar.iran.liara.run/public/${parseInt(lead.id) + 40}`} className="w-full h-full object-cover" alt="" />
                                </div>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    </motion.div>
                  ))}
                  <button className="w-full py-2.5 rounded-lg border border-dashed border-zinc-800 text-[11px] font-bold text-zinc-600 hover:text-zinc-500 hover:bg-zinc-900/30 transition-all mt-1">
                    + Add New
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
